# Generated by Django 4.2.30 on 2026-06-12 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosMasVendidosView',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('unidades_vendidas', models.IntegerField()),
                ('ingresos_totales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('veces_pedido', models.IntegerField()),
            ],
            options={
                'db_table': 'v_productos_mas_vendidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentasDiarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_pedidos', models.IntegerField(default=0)),
                ('ticket_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('producto_top', models.ForeignKey(blank=True, db_column='id_producto_top', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.producto')),
            ],
            options={
                'verbose_name_plural': 'ventas_diarias',
                'db_table': 'ventas_diarias',
            },
        ),
    ]
