# Generated by Django 4.2.30 on 2026-06-12 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_oferta_cantidad_vendida_oferta_limite_cantidad'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='oferta',
            field=models.ForeignKey(blank=True, db_column='id_oferta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.oferta'),
        ),
    ]
