# Generated by Django 4.2.30 on 2026-06-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='cantidad_vendida',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='oferta',
            name='limite_cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
