# Generated by Django 6.0.5 on 2026-05-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='comprobantes/')),
                ('monto_detectado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hash_imagen', models.CharField(blank=True, max_length=64, unique=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('validado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'comprobantes',
            },
        ),
        migrations.CreateModel(
            name='QRKiosko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=255)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50)),
                ('imagen_qr', models.ImageField(upload_to='qr_kiosko/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qr_kiosko',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente_validacion', 'Pendiente validación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente_validacion', max_length=30)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('notas_validacion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'transacciones',
            },
        ),
    ]
