# Generated by Django 4.2.30 on 2026-06-12 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRKiosko',
            fields=[
                ('id', models.AutoField(db_column='id_qr', primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=255)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen_qr', models.ImageField(db_column='imagen_qr_url', upload_to='qr_kiosko/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qr_kiosko',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(db_column='id_transaccion', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente_validacion', 'Pendiente validación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente_validacion', max_length=30)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('notas_validacion', models.TextField(blank=True, null=True)),
                ('pedido', models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.PROTECT, related_name='transaccion', to='pedidos.pedido')),
                ('qr_usado', models.ForeignKey(db_column='id_qr_usado', on_delete=django.db.models.deletion.PROTECT, to='pagos.qrkiosko')),
                ('validado_por', models.ForeignKey(blank=True, db_column='validado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transacciones',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(db_column='id_comprobante', primary_key=True, serialize=False)),
                ('imagen', models.ImageField(db_column='imagen_url', upload_to='comprobantes/')),
                ('monto_detectado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hash_imagen', models.CharField(blank=True, max_length=64, unique=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('validado', models.BooleanField(default=False)),
                ('transaccion', models.ForeignKey(db_column='id_transaccion', on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='pagos.transaccion')),
            ],
            options={
                'db_table': 'comprobantes',
            },
        ),
    ]
