# Generated by Django 6.0.5 on 2026-05-25 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaccion', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='qr_usado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.qrkiosko'),
        ),
    ]
