# Generated by Django 4.2.30 on 2026-06-12 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('codigo_estudiante', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('verificado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_acceso', null=True)),
                ('rol', models.ForeignKey(db_column='id_rol', default=2, on_delete=django.db.models.deletion.PROTECT, to='usuarios.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
